name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: install libjson-c
      run: sudo apt-get install libjson-c-dev
    - name: make check
      run: cd testsute && ./runtests.sh

